main/urls.py
from django.urls import path

from .views import tambahkegiatan, tambahpeserta, hapuspeserta, listkegiatan, halamandepan

app_name = 'main'

urlpatterns = [
    path('', halamandepan, name='halamandepan'),
    path('tambahkegiatan/', tambahkegiatan, name='tambahkegiatan'),
    path('tambahkegiatan/listkegiatan/', listkegiatan, name='listkegiatan'),
    path('listkegiatan/<int:my_id>/tambahpeserta/', tambahpeserta, name='tambahpeserta'),
    path('listkegiatan/<int:my_id>/hapuspeserta/', hapuspeserta, name='hapuspeserta'),
]

story6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

main/models.py
from django.db import models

class Kegiatan (models.Model):
    namakegiatan = models.CharField(max_length=50)
    deskripsi = models.TextField()

    def __str__(self):
        return self.namakegiatan

class peserta (models.Model):
    namaorang = models.CharField(max_length=50)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return self.namaorang

main/forms.py
from django import forms
from .models import Kegiatan, peserta

class formkegiatan(forms.ModelForm):

    class Meta:
        model = Kegiatan
        fields = ['namakegiatan', 'deskripsi']

    title_attrs = {
        'type': 'text',
        'class': 'form-namakegiatan',
        'placeholder':'Masukan nama kegiatan...'
    }

    desc_attrs = {
        'type': 'text',
        'class': 'form-deskripsi',
        'placeholder':'Masukan deskripsi...'
    }

    namakegiatan = forms.CharField(required=True, widget=forms.TextInput(attrs=title_attrs))
    deskripsi = forms.CharField(widget=forms.Textarea(attrs=desc_attrs))

    namakegiatan.widget.attrs.update({'class':'form-control'})
    deskripsi.widget.attrs.update({'class':'form-control'})

class formpeserta(forms.ModelForm):

    class Meta:
        model = peserta
        fields = ['namaorang']

    title_attrs = {
    'type': 'text',
    'class': 'form-namapeserta',
    'placeholder':'Masukan nama peserta...'
}

    namaorang = forms.CharField(required=True,widget=forms.TextInput(attrs=title_attrs))
    namaorang.widget.attrs.update({'class':'form-control'})

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import formkegiatan, formpeserta
from .models import Kegiatan, peserta

def halamandepan(request):
    return render(request, 'main/halamandepan.html')

def tambahkegiatan(request):
    form = formkegiatan(request.POST or None)
    if form.is_valid():
        form.save()
        form = Kegiatan()
        return redirect('main:listkegiatan')
    context = {
        'form' : form
    }
    return render(request, 'main/tambahkegiatan.html', context)

def listkegiatan (request):
    kegiatan = Kegiatan.objects.all()
    pesertaid = peserta.objects.all()
    context = {
        'kegiatan' : kegiatan,
        'pesertaid' : pesertaid
    }
    return render(request, 'main/listkegiatan.html', context)

def tambahpeserta(request, my_id):
    form = formpeserta(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            instance = form.save(commit=False)
            instance.kegiatan = Kegiatan.objects.get(id=my_id)
            instance.save()
        return redirect('main:listkegiatan')
        
    response = {
        'form': form
    }
    return render(request, 'main/tambahpeserta.html', response)

def hapuspeserta(request, my_id):
    pesertaid = peserta.objects.get(id=my_id)
    if request.method == "POST":
        pesertaid.delete()
        return redirect('main:listkegiatan')
        
    response = {
        'pesertaid': pesertaid
    }
    return render(request, 'main/hapuspeserta.html', response)

main/templates/main/halamandepan.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>KegiatanKU.</title>
{% endblock meta %} 
{% block content %}

<header>
  <div class="container">
    <div class="banner-text">
      <div class="text-area">
        <h1>KegiatanKU.</h1>
        <h2>Atur kegiatan kamu beserta orang yang kamu percayai</h2>
        <p class="banner-btn">
          <a href="{% url 'main:tambahkegiatan'%}" class="active">Tambah Kegiatan</a>
          <a href="{% url 'main:listkegiatan'%}" class="active">Lihat Kegiatan</a>
        </p>
      </div>
    </div>
  </div>
</header>

{% endblock content %}

main/templates/main/hapuspeserta.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hapus Peserta</title>
{% endblock meta %}

{% block content %}
<br>
<br>
  <div class="container">
    <form method="POST">
        {% csrf_token %} 
        <h2>Apakah kamu ingin menghapus peserta "{{pesertaid.namaorang}}" ?</h2>
        <p>Jika sudah terhapus, maka data tidak dapat dikembalikan lagi</p>
        <button type="Submit" class="btn btn-danger"value="Hapus">Hapus</button>
        <a href="{% url 'main:listkegiatan'%}" class="btn btn-primary" class="active">Batal</a>
    </form>
    
    
  </div>{% endblock content %}

main/templates/main/listkegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar KegiatanKu</title>
{% endblock meta %}

{% block content %}


<div class="container">
	<div class="col-md-12 d-flex justify-content-center mt-5">
      <h1 style="font-family: Rubik, sans-serif">Daftar Kegiatan</h2>
    </div>
  </div>
  <div class="container">
    <div class="col-md-12 d-flex justify-content-center mt-2">
        <p style="font-family: Rubik, sans-serif">Inilah daftar kegiatan beserta peserta yang ikut</p>
      </div>
    </div>
  <div class="container">
	<div class="col-lg-12 d-flex justify-content-center mt-3">
        <a class='btn btn-primary' href="{% url 'main:halamandepan'%}"">Kembali</a>
    </div>
  </div>

  <div class="col-lg-12 d-flex justify-content-center mt-3">
    <a class='btn btn-success' href="{% url 'main:tambahkegiatan'%}"">Tambah Kegiatan</a>
</div>
</div>
  <div class="container">
	<div class="col-md-12 d-flex justify-content-center mt-4">
        <span>Tombol merah untuk menghapus peserta</span>
  </div>
</div>
{% for kegiatan in kegiatan %}
<div class="row">

</div>
<div class="col-sm-12 d-flex justify-content-center mt-4">
<!-- <div class="container sm-10"> -->
    <div class="card" style="width: 24rem;">
        <img src= "{% static 'img/background.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{kegiatan.namakegiatan}}</h5>
          <span>Desc:</span>
          <p class="card-text">{{kegiatan.deskripsi}}</p>
          <span>Peserta:</span>
        </div>
        
        <ul class="list-group list-group-flush">
            
        {% for pesertaid in pesertaid %}
            {% if pesertaid.kegiatan == kegiatan %}

            <li class="list-group-item">{{pesertaid.namaorang}}  <br>
              <a href="{%url 'main:hapuspeserta' pesertaid.id%}" class="btn btn-danger"></a>

       </li>
          {%endif%}
          {% endfor %}
        </ul>
        
        <div class="card-body">
          <a href="{% url 'main:tambahpeserta' kegiatan.id%}" class="card-link">Tambah peserta</a>
        </div>
    </div>
    <br>
<!-- </div> -->
</div>
{% endfor %}
<br>
<br>



{% endblock content %}

main/templates/main/tambahkegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tambah KegiatanKu</title>
{% endblock meta %}

{% block content %}
<div class="container">
	<div class="col-md-12 d-flex justify-content-center mt-5">
	  <h1 style="font-family: Rubik, sans-serif">Tambah Kegiatan Kamu !</h2>
	</div>
  </div>
  <div class="container">
	<div class="col-md-12 d-flex justify-content-center mt-1">
	  <p style="font-family: Rubik, sans-serif">
		Kegiatan kamu nantinya akan menjadi terorganisir bersama orang-orang yang kamu percayai
	  </p>
	</div>
  </div>

  <div class="container mt-2">
	<div class="row d-flex justify-content-center">
	  <div class="col-lg-6">
		<div class="form-group">
		  <form method="POST" style="font-family: Rubik, sans-serif">
			{% csrf_token %} {{form.as_p}}
			<br />
			<button type="Submit" class="btn btn-success">Save</button>
			<a class= 'btn btn-primary' href="{% url 'main:halamandepan'%}" class="active">Kembali</a>
			<a class= 'btn btn-primary' href="{% url 'main:listkegiatan'%}" class="active">Lihat Kegiatan</a>
			<br />
		  </form>
		</div>
	  </div>
	</div>
  </div>
  <br>
  <br>


{% endblock content %}

main/templates/main/tambahpeserta.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tambah Peserta</title>
{% endblock meta %}

{% block content %}

<div class="container">
	<div class="col-md-12 d-flex justify-content-center mt-5">
	  <h1 style="font-family: Rubik, sans-serif">Tambah Peserta</h2>
	</div>
  </div>
  <div class="container">
	<div class="col-md-12 d-flex justify-content-center mt-1">
	  <p style="font-family: Rubik, sans-serif">
		Tambah peserta di kegiatan tertentu
	  </p>
	</div>
  </div>

  <div class="container mt-2">
	<div class="row d-flex justify-content-center">
	  <div class="col-lg-6">
		<div class="form-group">
		  <form method="POST" style="font-family: Rubik, sans-serif">
			{% csrf_token %} {{form.as_p}}
			<br />
			<button type="Submit" class="btn btn-success">Simpan</button>
			<a class= 'btn btn-primary' href="{% url 'main:listkegiatan'%}" class="active">Kembali</a>
			<br />
		  </form>
		</div>
	  </div>
	</div>
 </div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
crossorigin="anonymous"
/>
<link rel="stylesheet" href="{% static 'css/style1.css' %}">

    {% block meta %} {% endblock meta %}
  </head>

  <body></body>
  {% block content %} {% endblock content %}

  <script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"
></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"
></script>

</html>